### PR TITLE
fix(logs): Update the array index for determining the color category

### LINKED ISSUE #408: Colorizing of log message is currently broken
While we are correctly parsing off the pod name from the log message the conditional used to setup the color of the message is using the wrong array check.

### PR DESCRIPTION
**Pull request by jchauncey**
fixes #408

### CODE REVIEW

File: client/cmd/apps.go [hunk 1]
```diff
@@ -175,8 +175,8 @@ func printLogs(logs string) error {
 	for _, log := range strings.Split(logs, `\\n\\n`) {
 		category := "unknown"
 		parts := strings.Split(strings.Split(log, " -- ")[0], " ")
-		if len(parts) >= 2 {
-			category = parts[1]
+		if len(parts) >= 1 {
```
Comment (bacongobbler) [inline client/cmd/apps.go]: I don't think this check is needed any more. `strings.Split()` will always return a []string with a length >= 1. This was just to make sure that the string itself had been split at least once.

Comment (jchauncey) [inline client/cmd/apps.go]: Ok I'll try that out and resubmit (need to rebase anyways)
